//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SilverlightMediaFramework.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SilverlightMediaFrameworkResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SilverlightMediaFrameworkResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SilverlightMediaFramework.Core.Resources.SilverlightMediaFrameworkResou" +
                            "rces", typeof(SilverlightMediaFrameworkResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition of External Package Has Completed: {0}.
        /// </summary>
        internal static string AddExternalPackageCompletedLogMessage {
            get {
                return ResourceManager.GetString("AddExternalPackageCompletedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Progress of external package ({0}) is {1}.
        /// </summary>
        internal static string AddExternalPackageDownloadProgressChangedLogMessage {
            get {
                return ResourceManager.GetString("AddExternalPackageDownloadProgressChangedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition of External Package ({0}) Has Failed: {1}.
        /// </summary>
        internal static string AddExternalPackageFailedLogMessage {
            get {
                return ResourceManager.GetString("AddExternalPackageFailedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad not handled: {0}.
        /// </summary>
        internal static string AdNotHandled {
            get {
                return ResourceManager.GetString("AdNotHandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad skipped due to fast forward or rewind: {0}.
        /// </summary>
        internal static string AdSkippedFromFwdRwd {
            get {
                return ResourceManager.GetString("AdSkippedFromFwdRwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad skipped due to seek: {0}.
        /// </summary>
        internal static string AdSkippedFromSeek {
            get {
                return ResourceManager.GetString("AdSkippedFromSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffering Progress Changed: {0}.
        /// </summary>
        internal static string BufferingProgressChangedLogMessage {
            get {
                return ResourceManager.GetString("BufferingProgressChangedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption Region Left - Id: &quot;{0}&quot;.
        /// </summary>
        internal static string CaptionRegionLeftLogMessage {
            get {
                return ResourceManager.GetString("CaptionRegionLeftLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption Region Reached - Id: &quot;{0}&quot;.
        /// </summary>
        internal static string CaptionRegionReachedLogMessage {
            get {
                return ResourceManager.GetString("CaptionRegionReachedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified Chapter Item does not belong to the current Playlist..
        /// </summary>
        internal static string ChapterItemDoesNotBelongToCurrentPlaylistMessage {
            get {
                return ResourceManager.GetString("ChapterItemDoesNotBelongToCurrentPlaylistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured Video Size - Height: {0} Width: {1}.
        /// </summary>
        internal static string ConfiguredVideoSizeLogMessage {
            get {
                return ResourceManager.GetString("ConfiguredVideoSizeLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occurred Configuring Media Plugin: {0}.
        /// </summary>
        internal static string ConfigureMediaPluginFailedLogMessage {
            get {
                return ResourceManager.GetString("ConfigureMediaPluginFailedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity: &quot;{0}&quot; Sender: &quot;{1}&quot; Message: &quot;{2}&quot; Timestamp: &quot;{3}&quot;.
        /// </summary>
        internal static string DebugLogWriterOutputFormat {
            get {
                return ResourceManager.GetString("DebugLogWriterOutputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Progress Changed: {0}.
        /// </summary>
        internal static string DownloadProgressChangedLogMessage {
            get {
                return ResourceManager.GetString("DownloadProgressChangedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration Changed: {0}.
        /// </summary>
        internal static string DurationChangedLogMessage {
            get {
                return ResourceManager.GetString("DurationChangedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Playlist.
        /// </summary>
        internal static string errorInvalidPlaylist {
            get {
                return ResourceManager.GetString("errorInvalidPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Playlist: Unexpected node: {0} in {1}.
        /// </summary>
        internal static string errorInvalidPlaylistNode {
            get {
                return ResourceManager.GetString("errorInvalidPlaylistNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occurred - Location: &quot;{0}&quot; Message: &quot;{1}&quot;.
        /// </summary>
        internal static string GenericErrorOccurredLogMessage {
            get {
                return ResourceManager.GetString("GenericErrorOccurredLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Plugins Loaded.
        /// </summary>
        internal static string GenericPluginsLoadedLogMessage {
            get {
                return ResourceManager.GetString("GenericPluginsLoadedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient quota space to store resource.  Resource size: {0}..
        /// </summary>
        internal static string InsufficientQuotaSpaceToStoreResourcesErrorMessage {
            get {
                return ResourceManager.GetString("InsufficientQuotaSpaceToStoreResourcesErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred loading a plugin - Plugin: &quot;{0}&quot; Error: &quot;{1}&quot;.
        /// </summary>
        internal static string LoadPluginFailedLogMessage {
            get {
                return ResourceManager.GetString("LoadPluginFailedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3} Severity: &quot;{0}&quot; Sender: &quot;{1}&quot; Type: &quot;{2}&quot; Message: &quot;{3}&quot; .
        /// </summary>
        internal static string LoggingOutputFormat {
            get {
                return ResourceManager.GetString("LoggingOutputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded LogWriter Plugins.
        /// </summary>
        internal static string LogWritersLoadedLogMessage {
            get {
                return ResourceManager.GetString("LogWritersLoadedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marker Left - Type: &quot;{0}&quot; Begin: &quot;{1}&quot; End: &quot;{2}&quot;.
        /// </summary>
        internal static string MarkerLeftLogMessage {
            get {
                return ResourceManager.GetString("MarkerLeftLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marker Provider Registered: {0}.
        /// </summary>
        internal static string MarkerProviderRegisteredLogMessage {
            get {
                return ResourceManager.GetString("MarkerProviderRegisteredLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marker Provider Unregistered: {0}.
        /// </summary>
        internal static string MarkerProviderUnregisteredLogMessage {
            get {
                return ResourceManager.GetString("MarkerProviderUnregisteredLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marker Reached - Type: &quot;{0}&quot; Begin: &quot;{1}&quot; End: &quot;{2}&quot;.
        /// </summary>
        internal static string MarkerReachedLogMessage {
            get {
                return ResourceManager.GetString("MarkerReachedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marker Skipped - Type: &quot;{0}&quot; Begin: &quot;{1}&quot; End: &quot;{2}&quot;.
        /// </summary>
        internal static string MarkerSkippedLogMessage {
            get {
                return ResourceManager.GetString("MarkerSkippedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markers Removed: {0}.
        /// </summary>
        internal static string MarkersRemovedLogMessage {
            get {
                return ResourceManager.GetString("MarkersRemovedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Bitrate Changed: {0}.
        /// </summary>
        internal static string MaximumBitrateChangedLogMessage {
            get {
                return ResourceManager.GetString("MaximumBitrateChangedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Ended.
        /// </summary>
        internal static string MediaEndedLogMessage {
            get {
                return ResourceManager.GetString("MediaEndedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Failed: {0}.
        /// </summary>
        internal static string MediaFailedLogMessage {
            get {
                return ResourceManager.GetString("MediaFailedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Opened.
        /// </summary>
        internal static string MediaOpenedLogMessage {
            get {
                return ResourceManager.GetString("MediaOpenedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Plug In Registered: {0}.
        /// </summary>
        internal static string MediaPluginRegisteredLogMessage {
            get {
                return ResourceManager.GetString("MediaPluginRegisteredLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Plug In Unregistered: {0}.
        /// </summary>
        internal static string MediaPluginUnregisteredLogMessage {
            get {
                return ResourceManager.GetString("MediaPluginUnregisteredLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Markers: {0}.
        /// </summary>
        internal static string NewMarkersLogMessage {
            get {
                return ResourceManager.GetString("NewMarkersLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Failed For {0} Stream Length is {1}..
        /// </summary>
        internal static string OfflineDownloadFailedErrorMessage {
            get {
                return ResourceManager.GetString("OfflineDownloadFailedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback Bitrate Changed: {0}.
        /// </summary>
        internal static string PlaybackBitrateChangedLogMessage {
            get {
                return ResourceManager.GetString("PlaybackBitrateChangedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayBlock added by {0}.
        /// </summary>
        internal static string PlayBlockAdded {
            get {
                return ResourceManager.GetString("PlayBlockAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayBlock released by {0}.
        /// </summary>
        internal static string PlayBlockReleased {
            get {
                return ResourceManager.GetString("PlayBlockReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist Changed.
        /// </summary>
        internal static string PlaylistChangedLogMessage {
            get {
                return ResourceManager.GetString("PlaylistChangedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist Item Changed.
        /// </summary>
        internal static string PlaylistItemChangedLogMessage {
            get {
                return ResourceManager.GetString("PlaylistItemChangedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Speed Changed: {0}.
        /// </summary>
        internal static string PlaySpeedChangedLogMessage {
            get {
                return ResourceManager.GetString("PlaySpeedChangedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play State Changed: {0}.
        /// </summary>
        internal static string PlayStateChangedLogMessage {
            get {
                return ResourceManager.GetString("PlayStateChangedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable To Load Plugin ({0}) the following error has occurred: {1}.
        /// </summary>
        internal static string PluginLoadFailedLogMessage {
            get {
                return ResourceManager.GetString("PluginLoadFailedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Plugins Loaded.
        /// </summary>
        internal static string PluginsLoaded3DLogMessage {
            get {
                return ResourceManager.GetString("PluginsLoaded3DLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdPayloadHandler Plugins Loaded.
        /// </summary>
        internal static string PluginsLoadedAdPayloadHandlerLogMessage {
            get {
                return ResourceManager.GetString("PluginsLoadedAdPayloadHandlerLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string readerChapterItem {
            get {
                return ResourceManager.GetString("readerChapterItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show chapters toggle.
        /// </summary>
        internal static string readerChapters {
            get {
                return ResourceManager.GetString("readerChapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed captions toggle.
        /// </summary>
        internal static string readerClosedCaptions {
            get {
                return ResourceManager.GetString("readerClosedCaptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step backwards one frame.
        /// </summary>
        internal static string readerFrameStepBackwards {
            get {
                return ResourceManager.GetString("readerFrameStepBackwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step forwards one frame.
        /// </summary>
        internal static string readerFrameStepForwards {
            get {
                return ResourceManager.GetString("readerFrameStepForwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full screen toggle.
        /// </summary>
        internal static string readerFullScreen {
            get {
                return ResourceManager.GetString("readerFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one hour.
        /// </summary>
        internal static string readerHour {
            get {
                return ResourceManager.GetString("readerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours.
        /// </summary>
        internal static string readerHours {
            get {
                return ResourceManager.GetString("readerHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one minute.
        /// </summary>
        internal static string readerMinute {
            get {
                return ResourceManager.GetString("readerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        internal static string readerMinutes {
            get {
                return ResourceManager.GetString("readerMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute Toggle.
        /// </summary>
        internal static string readerMute {
            get {
                return ResourceManager.GetString("readerMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to next marker.
        /// </summary>
        internal static string readerNextMarker {
            get {
                return ResourceManager.GetString("readerNextMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make player available offline.
        /// </summary>
        internal static string readerOffline {
            get {
                return ResourceManager.GetString("readerOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the cancel button to stop offline installation.
        /// </summary>
        internal static string readerOfflineProgressCancel {
            get {
                return ResourceManager.GetString("readerOfflineProgressCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the finish button to compete offline installation.
        /// </summary>
        internal static string readerOfflineProgressFinish {
            get {
                return ResourceManager.GetString("readerOfflineProgressFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show playlist toggle.
        /// </summary>
        internal static string readerPlaylist {
            get {
                return ResourceManager.GetString("readerPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playlist item {0}. {1}..
        /// </summary>
        internal static string readerPlaylistItem {
            get {
                return ResourceManager.GetString("readerPlaylistItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play pause toggle.
        /// </summary>
        internal static string readerPlayPause {
            get {
                return ResourceManager.GetString("readerPlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show graphs.
        /// </summary>
        internal static string readerPlugin {
            get {
                return ResourceManager.GetString("readerPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show player in seperate window.
        /// </summary>
        internal static string readerPopout {
            get {
                return ResourceManager.GetString("readerPopout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to previous marker.
        /// </summary>
        internal static string readerPreviousMarker {
            get {
                return ResourceManager.GetString("readerPreviousMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one second.
        /// </summary>
        internal static string readerSecond {
            get {
                return ResourceManager.GetString("readerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds.
        /// </summary>
        internal static string readerSeconds {
            get {
                return ResourceManager.GetString("readerSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek to time.
        /// </summary>
        internal static string readerSeekSlider {
            get {
                return ResourceManager.GetString("readerSeekSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string readerStop {
            get {
                return ResourceManager.GetString("readerStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease volume.
        /// </summary>
        internal static string readerVolumeDown {
            get {
                return ResourceManager.GetString("readerVolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set volume.
        /// </summary>
        internal static string readerVolumeSlider {
            get {
                return ResourceManager.GetString("readerVolumeSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase volume.
        /// </summary>
        internal static string readerVolumeUp {
            get {
                return ResourceManager.GetString("readerVolumeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Markers Has Failed: {0}.
        /// </summary>
        internal static string RetrieveMarkersFailedLogMessage {
            get {
                return ResourceManager.GetString("RetrieveMarkersFailedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry Attempt Failed: {0}.
        /// </summary>
        internal static string RetryAttemptFailedLogMessage {
            get {
                return ResourceManager.GetString("RetryAttemptFailedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry Cancelled.
        /// </summary>
        internal static string RetryCancelledLogMessage {
            get {
                return ResourceManager.GetString("RetryCancelledLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry Failed.
        /// </summary>
        internal static string RetryFailedLogMessage {
            get {
                return ResourceManager.GetString("RetryFailedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to begin retrying, MediaElementPlugin cannot be null..
        /// </summary>
        internal static string RetryMonitorMediaPluginCannotBeNullMessage {
            get {
                return ResourceManager.GetString("RetryMonitorMediaPluginCannotBeNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry Started.
        /// </summary>
        internal static string RetryStartedLogMessage {
            get {
                return ResourceManager.GetString("RetryStartedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry Successful.
        /// </summary>
        internal static string RetrySuccessfulLogMessage {
            get {
                return ResourceManager.GetString("RetrySuccessfulLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timecode frame value is not in the expected range for SMPTE 23.98 IVTC..
        /// </summary>
        internal static string Smpte12M_2398_BadFormat {
            get {
                return ResourceManager.GetString("Smpte12M_2398_BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timecode frame value is not in the expected range for SMPTE 24fps Film Sync..
        /// </summary>
        internal static string Smpte12M_24_BadFormat {
            get {
                return ResourceManager.GetString("Smpte12M_24_BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timecode frame value is not in the expected range for SMPTE 25fps PAL..
        /// </summary>
        internal static string Smpte12M_25_BadFormat {
            get {
                return ResourceManager.GetString("Smpte12M_25_BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timecode frame value is not in the expected range for SMPTE 29.97 DropFrame..
        /// </summary>
        internal static string Smpte12M_2997_Drop_BadFormat {
            get {
                return ResourceManager.GetString("Smpte12M_2997_Drop_BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timecode frame value is not in the expected range for SMTPE 29.97 NonDrop..
        /// </summary>
        internal static string Smpte12M_2997_NonDrop_BadFormat {
            get {
                return ResourceManager.GetString("Smpte12M_2997_NonDrop_BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timecode frame value is not in the expected range for SMPTE 30fps..
        /// </summary>
        internal static string Smpte12M_30_BadFormat {
            get {
                return ResourceManager.GetString("Smpte12M_30_BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timecode provided is not in the correct format..
        /// </summary>
        internal static string Smpte12MBadFormat {
            get {
                return ResourceManager.GetString("Smpte12MBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timecode provided is out of the expected range..
        /// </summary>
        internal static string Smpte12MOutOfRange {
            get {
                return ResourceManager.GetString("Smpte12MOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resulting timecode is out of the expected range of MaxValue..
        /// </summary>
        internal static string Smpte12MOverflowException {
            get {
                return ResourceManager.GetString("Smpte12MOverflowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Plugins Loaded.
        /// </summary>
        internal static string UIPluginsLoadedLogMessage {
            get {
                return ResourceManager.GetString("UIPluginsLoadedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable To Locate The Correct Marker Provider For This Media.
        /// </summary>
        internal static string UnableToLocateMarkerProviderLogMessage {
            get {
                return ResourceManager.GetString("UnableToLocateMarkerProviderLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable To Locate A Media Plugin To Play This Media.
        /// </summary>
        internal static string UnableToLocateMediaPluginLogMessage {
            get {
                return ResourceManager.GetString("UnableToLocateMediaPluginLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This delivery method is not supported by the current Plugin: {0}.
        /// </summary>
        internal static string UnsupportedAdDeliveryMethodExceptionMessage {
            get {
                return ResourceManager.GetString("UnsupportedAdDeliveryMethodExceptionMessage", resourceCulture);
            }
        }
    }
}
