//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SilverlightMediaFramework.Plugins.SmoothStreaming.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SmoothStreamingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SmoothStreamingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SilverlightMediaFramework.Plugins.SmoothStreaming.Resources.SmoothStrea" +
                            "mingResources", typeof(SmoothStreamingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The download of stream data has timed out..
        /// </summary>
        internal static string DownloadStreamDataTimeOutExceptionMessage {
            get {
                return ResourceManager.GetString("DownloadStreamDataTimeOutExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To schedule an ad you must specify either a valid start time or an existing ad to append to..
        /// </summary>
        internal static string ScheduleAdInvalidArgumentsExceptionMessage {
            get {
                return ResourceManager.GetString("ScheduleAdInvalidArgumentsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Element Generated Log - Reason: {0}.
        /// </summary>
        internal static string SmoothStreamingMediaElementGeneratedLogMessageFormat {
            get {
                return ResourceManager.GetString("SmoothStreamingMediaElementGeneratedLogMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmoothStreamingMediaPlugin Instantiated.
        /// </summary>
        internal static string SmoothStreamingMediaPluginInstantiatedLogMessage {
            get {
                return ResourceManager.GetString("SmoothStreamingMediaPluginInstantiatedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmoothStreamingMediaPlugin Loaded.
        /// </summary>
        internal static string SmoothStreamingMediaPluginLoadedLogMessage {
            get {
                return ResourceManager.GetString("SmoothStreamingMediaPluginLoadedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmoothStreamingMediaPlugin Load Failed: {0}.
        /// </summary>
        internal static string SmoothStreamingMediaPluginLoadFailedLogMessage {
            get {
                return ResourceManager.GetString("SmoothStreamingMediaPluginLoadFailedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmoothStreamingMediaPlugin Unloaded.
        /// </summary>
        internal static string SmoothStreamingMediaPluginUnloadedLogMessage {
            get {
                return ResourceManager.GetString("SmoothStreamingMediaPluginUnloadedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmoothStreamingMediaPlugin Unload Failed: {0}.
        /// </summary>
        internal static string SmoothStreamingMediaPluginUnloadFailedLogMessage {
            get {
                return ResourceManager.GetString("SmoothStreamingMediaPluginUnloadFailedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream Selection Failed..
        /// </summary>
        internal static string StreamSelectionFailedMessage {
            get {
                return ResourceManager.GetString("StreamSelectionFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline Marker Reached - Time: {0} Type: {1} Text: {2}.
        /// </summary>
        internal static string TimelineMarkerReached {
            get {
                return ResourceManager.GetString("TimelineMarkerReached", resourceCulture);
            }
        }
    }
}
