//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SilverlightMediaFramework.Plugins.TimedText.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TimedTextMediaPluginResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TimedTextMediaPluginResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SilverlightMediaFramework.Plugins.TimedText.Resources.TimedTextMediaPlu" +
                            "ginResources", typeof(TimedTextMediaPluginResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Completed.
        /// </summary>
        internal static string DownloadCompletedLogMessage {
            get {
                return ResourceManager.GetString("DownloadCompletedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Failed: {0}.
        /// </summary>
        internal static string DownloadFailedLogMessage {
            get {
                return ResourceManager.GetString("DownloadFailedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Progress Changed: {0}.
        /// </summary>
        internal static string DownloadProgressChangedLogMessage {
            get {
                return ResourceManager.GetString("DownloadProgressChangedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing of DFXP data failed: {0}.
        /// </summary>
        internal static string InStreamTimedTextPluginParseDFXPFailedLogMessage {
            get {
                return ResourceManager.GetString("InStreamTimedTextPluginParseDFXPFailedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing of DFXP data completed.  {0} captions added..
        /// </summary>
        internal static string InStreamTimedTextPluginParsingSuccessfulLogMessage {
            get {
                return ResourceManager.GetString("InStreamTimedTextPluginParsingSuccessfulLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse Error: {0}.
        /// </summary>
        internal static string ParseErrorLogMessage {
            get {
                return ResourceManager.GetString("ParseErrorLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimedTextMediaPlugin Instantiated.
        /// </summary>
        internal static string TimedTextMediaPluginInstantiatedLogMessage {
            get {
                return ResourceManager.GetString("TimedTextMediaPluginInstantiatedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimedTextMediaPlugin Loaded.
        /// </summary>
        internal static string TimedTextMediaPluginLoadedLogMessage {
            get {
                return ResourceManager.GetString("TimedTextMediaPluginLoadedLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimedTextMediaPlugin Unloaded.
        /// </summary>
        internal static string TimedTextMediaPluginUnloadedLogMessage {
            get {
                return ResourceManager.GetString("TimedTextMediaPluginUnloadedLogMessage", resourceCulture);
            }
        }
    }
}
